name: otus
services:
    laravel:
        build:
            context: './8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'otus-laravel-sail'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '..:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    scheduler:
        build:
            context: './8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'otus-laravel-sail'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        command: 'scheduler.sh'
        volumes:
            - '..:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    # Laravel queue worker for transactional queue
    jobs_consumer:
        profiles:
            -   queues
        build:
            context: './8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'otus-laravel-sail'
        restart: unless-stopped
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        command: [ 'php', '/var/www/html/artisan', 'queue:work', 'database', '--queue=transactional' ]
        volumes:
            - '..:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - laravel

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    node:
        image: node:22-alpine
        restart: on-failure
        volumes:
            - ..:/app
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        working_dir: /app
        user: "1000:1000"
        # tail -F /dev/null нужна, чтобы при отсутствии зависимостей
        #          или другой ошибке в первой команде контейнер не останавливался
        command: sh -c "npm run dev || tail -F /dev/null"

    # Фейковый сервер почты
    # Доступен по адресу http://localhost:8025
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail


networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
